### ISSUE TITLE
[Enhancement] Better way to control draggable

### ISSUE THREAD

**Issue by fnaith** [BurningTreeC/tiddlywiki-multi-columns#1]
Excellent plugin, it almost perfect for multiple tiddler editing !

However, I found I can't copy text from tiddler but always dragging them.
I am assuming it is a CSS issue, because I installed too much plugin.

![plugins](https://user-images.githubusercontent.com/11421034/202843879-bf5beb30-9e42-457a-898a-31ff68e3ab9e.PNG)

I guess a more robust method to toggle dragging-enable will make this plugin better.

**Comment by BurningTreeC** [comment]
Hi @fnaith and sorry for the late reply!

Looking at your installed plugins I don't see anything that should cause problems (at first sight)
If you're still interested, I'll have a look at making the toggle more consistent.
Are you able to post a screen capture of the problem?

Thank you and kind regards

**Comment by fnaith** [comment]
I believe it works as excepted after I re-install tiddlywiki.
Many thanks !
